<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <!-- Parent Project -->
    <parent>
        <groupId>com.enterprise</groupId>
        <artifactId>enterprise-ecommerce</artifactId>
        <version>1.0.0</version>
    </parent>

    <!-- Current Module -->
    <artifactId>common-lib</artifactId>

    <dependencies>

        <!-- ================================================= -->
        <!-- Lombok                                            -->
        <!-- ================================================= -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>


        <!-- ================================================= -->
        <!-- JWT                                               -->
        <!-- ================================================= -->

        <!-- JWT create / parse / validate API -->
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-api</artifactId>
            <version>0.12.6</version>
        </dependency>

        <!-- JWT implementation -->
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-impl</artifactId>
            <version>0.12.6</version>
            <scope>runtime</scope>
        </dependency>

        <!-- Jackson support for JWT -->
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-jackson</artifactId>
            <version>0.12.6</version>
            <scope>runtime</scope>
        </dependency>


        <!-- ================================================= -->
        <!-- Spring Security Core                              -->
        <!-- ================================================= -->

        <!--
            JwtService / SecurityUtils ke liye:
            Authentication
            UserDetails
            SecurityContextHolder
            etc.
        -->
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>


        <!-- ================================================= -->
        <!-- Spring Web                                        -->
        <!-- ================================================= -->

        <!-- OncePerRequestFilter ke liye -->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
        </dependency>


        <!-- ================================================= -->
        <!-- Servlet API                                       -->
        <!-- ================================================= -->

        <!-- OncePerRequestFilter ke servlet request/response ke liye -->
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
        </dependency>

        <!-- Production-style reusable library ke liye Spring Boot AutoConfiguration use karenge.-->
        <!-- Spring Boot AutoConfiguration-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>

    </dependencies>

</project>